export const colleges = [
  {
    college_name: "IIT Madras (IITM) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg", 
    ranking: "7 in 260 colleges in north campus",
    rating: 4.5,
  },
  {
    college_name: "IIT Delhi (IITD) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 5,
  },
  {
    college_name: "IIT Bombay (IITB) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 4,
  },
  {
    college_name: "IIT Kharagpur (IITKGP) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 4.5,
  },
  {
    college_name: "IIT Kanpur (IITK)",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 4,
  },
  {
    college_name: "IIT Roorkee (IITR) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 5,
  },
  {
    college_name: "IIT Guwahati (IITG) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 4,
  },
  {
    college_name: "IIT Hyderabad (IITH) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 5,
  },
  {
    college_name: "IIT Bhubaneswar (IITBBS) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 4,
  },
  {
    college_name: "IIT Patna (IITP) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 4.5,
  },
  {
    college_name: "IIT Gandhinagar (IITGN) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 4,
  },
  {
    college_name: "IIT Ropar (IITRPR) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 4,
  },
  {
    college_name: "IIT Bhilai (IIT C) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 5,
  },
  {
    college_name: "IIT Jodhpur (IITJ) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 4,
  },
  {
    college_name: "IIT Ropar (IITRPR) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 4.5,
  },
  {
    college_name: "IIT Tirupati (IITTP) ",
    original_fees: 6000,
    discounted_fees: 5200,
    image: "/college.jpg",
    ranking: "7 in 260 colleges in north campus",
    rating: 4,
  },
];